trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscription: 'TerraformSP'
  functionAppName: 'httptriggeredfuctionapp'
  resourceGroupName: 'httptriggeredfuctionapp_group'
  dotnetVersion: '6.0.x'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: $(dotnetVersion)
  displayName: 'Install .NET SDK'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 5.x'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'
  displayName: 'Restore NuGet packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
  displayName: 'Build .NET Project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/publish_output'
    zipAfterPublish: true
  displayName: 'Publish .NET Project'

- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az functionapp deployment source config-zip -g $(resourceGroupName) -n $(functionAppName) --src $(Build.ArtifactStagingDirectory)/publish_output.zip
  displayName: 'Deploy to Azure Function App'

